---
- name: Ansible moudle
  hosts: stapp01, stapp02, stapp03
  become: yes
  tasks:
   - name: Create blank file
     file:
        path:  /home/code.txt
        state: touch
        mode: "0755"
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"
        
ansible all -a "ls -ltr /home/" -i inventory