apiVersion: v1
kind: Deployment
metadata:
  name: appdeployment
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
     app: nodeapp
  template:
    metadata:
       labels:
         app: nodeapp
    spec:
      containers:
        - name: nodeappcontainer
          image: gcr.io/kodekloud/centos-ssh-enabled:node
          ports:
            - containerPort: 80
