apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-datacenter
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /mnt/security
  
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-datacenter
  labels:
    app: mysql-app
spec:
  storageClassName: manual
  accessModes: 
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-datacenter
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: mysql-app
   
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-datacenter
  labels:
   app: mysql-app
spec:
  volumes:
    - name: pv1-nautilus
      persistentVolumeClaim:
        claimName: pvc-datacenter
  containers:
    - name: container-datacenter
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: pv1-nautilus