---
- name: created infile in anisible
  hosts: stapp01, stapp02, stapp03
  become: true
  become_method: sudo 
  tasks:
   - name: install the httpd
     yum: 
      name: httpd 
      state: latest
   - name: Creating emptyfile
     file: 
      path: /var/www/html/index.html
      state: touch  
   - name: Creating with content
     copy:
      dest: /var/www/html/index.html
      content: |
          This is a Nautilus sample file, created using Ansible!
   - name: Using lineinfile Ansible module add some more content 
     lineinfile:
        path: /var/www/html/index.html
        insertbefore: BOF
        line: 'Welcome to Nautilus Group!'
        owner: apache
        group: apache
        mode: "0777"                 
   - name: start the service
     service:
       name: httpd
       state: started

       
