apiVersion: v1

kind: Pod

metadata:

  name: secret-datacenter

  labels:

    name: myapp

spec:

  volumes:

    - name: secret-volume-devops

      secret:

        secretName: media

  containers:

    - name: secret-container-datacenter

      image: centos:latest

      command: ["/bin/bash", "-c", "sleep 10000"]

      volumeMounts:

        - name: secret-volume-devops

          mountPath: /opt/cluster

          readOnly: true