apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
  labels:
   app: myapp
spec:
  volumes:
    - name: volume-share 
      emptyDir: {}
  containers: 
    - name: volume-container-xfusion-1
      image: centos:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
       - name: volume-share
         mountPath:  /tmp/blog
    - name: volume-container-xfusion-1
      image: centos:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
       - name: volume-share
         mountPath: /tmp/demo
      

         
  