apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replicationcontroller
spec:
   replicas: 3
   selector:
     app: nginx_app
   template:
     metadata:
      name: nginx-replicationcontroller
      labels:
        app: nginx_app
        type: front-end
     spec:
       containers:
        - name:  nginx-container
          image: nginx_app
          ports:
            - containerPort: 80 



