kubectl create secret generic ecommerce --from-file=/opt/ecommerce.txt

apiVersion: v1
kind: Pod
metadata:
 name: secret-nautilus
spec:
 volumes:
  - name: secretsecret-volume-datacenter
    secret:
     secretName: ecommerce
 containers:
 - name: secret-container-nautilus 
    image: debian
   command: ["/bin/bash","-c","sleep 1000"]
   volumeMounts:
   - name: secretsecret-volume-datacenter
     mountPath: /opt/cluster
     readOnly: true  
