apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: devops 
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
     - port: 80
       nodePort: 30008
       targetPort: 8080

