apiVersion: v1
kind: Pod
metadata:
  name: pod-datacenter
  labels:
   app: mysql-app
spec:
  volumes:
    - name: pv-datacenter
      persistentVolumeClaim:
         claimName: pvc-datacenter
  containers:
    - name: container-datacenter
      image: nginx:latest
      volumeMounts:
        - mountPath: "/mnt/dba"
          name: pv-datacenter