apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-datacenter
  namespace: tomcat-namespace-datacenter
spec:
  type: NodePort
  selector:   
    app: tomcat
  ports:    
     - port: 80
       protocol: TCP
       nodePort: 32227
       targetPort: 8080
