apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-datacenter
  namespace: tomcat-namespace-datacenter
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
     app: tomcat
  template:
    metadata:
       labels:
         app: tomcat
    spec:
      containers:
        - name: tomcat-container-datacenter
          image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
          ports:
            - containerPort: 8080